In [101]:
import pandas as pd
import numpy as np
import seaborn as sns
data=pd.read_csv('/content/drive/MyDrive/Machine Learning/iris.csv')

In [102]:
data

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width      Class
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [103]:
x=data[['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width']]
y=data.Class

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(x,y, test_size=0.2, random_state=1)

In [106]:
len(X_train)

120

In [107]:
len(Y_train)

120

In [108]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)

In [110]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=10)

In [111]:
knn.score(X_test,Y_test)

0.9666666666666667

In [113]:
knn.predict([[4.8,3.5,1.2,0.2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['Setosa'], dtype=object)

In [114]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [115]:
dtree.predict([[4.8,3.5,1.2,0.2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['Setosa'], dtype=object)

In [116]:
from sklearn.ensemble import RandomForestClassifier
ranfor=RandomForestClassifier()
ranfor.fit(X_train,Y_train)

RandomForestClassifier()

In [117]:
ranfor.predict([[4.8,3.5,1.2,0.2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['Setosa'], dtype=object)

In [120]:
knn_pred=knn.predict(X_test)
dtree_pred=dtree.predict(X_test)
ranfor_pred=ranfor.predict(X_test)

In [119]:
from sklearn.metrics import classification_report, confusion_matrix

In [121]:
print(classification_report(Y_test,knn_pred))
print(confusion_matrix(Y_test,knn_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      0.92      0.96        13
   Virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [122]:
print(classification_report(Y_test,dtree_pred))
print(confusion_matrix(Y_test,dtree_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      0.92      0.96        13
   Virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [123]:
print(classification_report(Y_test,ranfor_pred))
print(confusion_matrix(Y_test,ranfor_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      0.92      0.96        13
   Virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
