In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
data=pd.read_csv('/content/drive/MyDrive/Machine Learning/titanic.csv')

In [36]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [37]:
data_n=data.drop(['PassengerId','Name','Ticket','SibSp','Parch','Fare','Cabin','Embarked'],axis='columns')

In [38]:
data_n.head()

Survived  Pclass     Sex   Age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [39]:
input=data_n.drop('Survived',axis='columns')
target=data_n.Survived

In [40]:
input.Sex=input.Sex.map({'male':1,'female':2})
input.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [41]:
input.Age=input.Age.fillna(input.Age.mean())
input.head()

Pclass  Sex   Age
0       3    1  22.0
1       1    2  38.0
2       3    2  26.0
3       1    2  35.0
4       3    1  35.0

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(input, target, test_size=0.2)

In [43]:
len(X_train)

712

In [44]:
len(X_test)

179

In [45]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [46]:
model.score(X_test, Y_test)

0.8379888268156425

In [54]:
model.predict(X_test)

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1])

In [55]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, model.predict(X_test)))
print(confusion_matrix(Y_test, model.predict(X_test))) 

              precision    recall  f1-score   support

           0       0.83      0.93      0.88       112
           1       0.85      0.69      0.76        67

    accuracy                           0.84       179
   macro avg       0.84      0.81      0.82       179
weighted avg       0.84      0.84      0.83       179

[[104   8]
 [ 21  46]]


In [57]:
from sklearn.ensemble import RandomForestClassifier
x1=RandomForestClassifier(n_estimators=100)
x1.fit(X_train, Y_train)

RandomForestClassifier()

In [59]:
x1.predict(X_test)

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1])

In [60]:
print(classification_report(Y_test, x1.predict(X_test)))
print(confusion_matrix(Y_test, x1.predict(X_test)))

              precision    recall  f1-score   support

           0       0.84      0.91      0.88       112
           1       0.83      0.72      0.77        67

    accuracy                           0.84       179
   macro avg       0.84      0.81      0.82       179
weighted avg       0.84      0.84      0.84       179

[[102  10]
 [ 19  48]]
