In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
data=pd.read_csv('/content/drive/MyDrive/Machine Learning/insurance_data.csv')

In [2]:
data

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [3]:
x=data['age']
y=data['bought_insurance']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(x,y, test_size=0.3, random_state=100)

In [5]:
X_train= X_train.values.reshape(-1, 1)
X_test = X_test.values.reshape(-1, 1)

In [6]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [7]:
pred=dtree.predict(X_test)
pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1])

In [8]:
from sklearn.metrics import classification_report, confusion_matrix

In [9]:
print(classification_report(Y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.83      1.00      0.91         5

    accuracy                           0.89         9
   macro avg       0.92      0.88      0.88         9
weighted avg       0.91      0.89      0.89         9



In [10]:
print(confusion_matrix(Y_test,pred))

[[3 1]
 [0 5]]


In [11]:
from sklearn.ensemble import RandomForestClassifier
x1=RandomForestClassifier(n_estimators=100)
x1.fit(X_train,Y_train)

RandomForestClassifier()

In [12]:
x1_pred=dtree.predict(X_test)

In [13]:
print(classification_report(Y_test,x1_pred))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.83      1.00      0.91         5

    accuracy                           0.89         9
   macro avg       0.92      0.88      0.88         9
weighted avg       0.91      0.89      0.89         9



In [14]:
print(confusion_matrix(Y_test,x1_pred))

[[3 1]
 [0 5]]
